version: '3.3'
services:
  db:
    image: postgres:9.6-alpine
  products-api:
    build:
      context: ../products-api
    command: rails s -p 3000 -b 0.0.0.0
    env_file: ../products-api/.env
    volumes:
      - ../products-api:/usr/src/app
    depends_on:
      - db
  shop:
    build: ./
    command: rails s -p 4000 -b 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - products-api
